"""Snakemake file defining the workflows
"""


configfile: "config/config.yaml"


include: "rules/base_coverage.smk"
include: "rules/amplicon_cov.smk"
# example workflow for testing unit tests
include: "rules/smk_testing.smk"


rule all:
    input:
        #"../results/statistics.csv",
        "results/20240705_AAFH52MM5/cov_heatmap.pdf",
