## Input paths
basecnt_tsv_dir: "/cluster/project/pangolin/work-vp-test/results/*/*/alignments/basecnt.tsv.gz"
total_coverage_dir: "/cluster/project/pangolin/work-vp-test/results/*/*/alignments/coverage.tsv.gz"
# singe file with colum [mut] listing mutation of interest in each row
mutations_of_interest_dir: "/cluster/home/koehng/temp/mutations_of_interest.csv"
# timeline file of columns [sample, batch, reads, proto, location_code, date, location]
timeline_fp: "/cluster/project/pangolin/work-vp-test/variants/timeline.tsv"

## Output directory
outdir: "/cluster/home/koehng/temp/"